FROM ubuntu:15.04

LABEL maintainer="Jagan Teki <jagan@edgeble.ai>"
LABEL release="pyro"

# Set up the non-interactive container build
ARG DEBIAN_FRONTEND=noninteractive

# Replace the default package repositories with an archived mirror
RUN sed -i -e 's|http://archive.ubuntu.com|http://old-releases.ubuntu.com|g' /etc/apt/sources.list
RUN sed -i -e 's|http://security.ubuntu.com|http://old-releases.ubuntu.com|g' /etc/apt/sources.list

# Set up locales
RUN apt-get update && apt-get install -y \
    apt-utils locales sudo && \
    dpkg-reconfigure locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LANG en_US.utf8

# Install packages listed in Yocto documentation as esential
RUN apt-get update && apt-get install -y \
    gawk \
    wget \
    git \
    diffstat \
    unzip \
    texinfo \
    gcc \
    build-essential \
    chrpath \
    socat \
    cpio \
    python3 \
    python3-pip \
    python3-pexpect \
    xz-utils \
    debianutils \
    iputils-ping \
    python3-jinja2 \
    libegl1-mesa \
    libsdl1.2-dev \
    xterm \
    python3-subunit \
    mesa-common-dev \
    liblz4-tool && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install and update ca-certificates
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-ca-certificates

RUN useradd -ms /bin/bash build
RUN usermod -aG sudo build
RUN echo "build ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/build

USER build
WORKDIR /home/build
